apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: miyatto/tasks-api:latest
          env:
            - name: AUTH_ADDRESS
              value: 'auth-service.default'
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
